# put kops config here
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prd.aws.rolwynquadras.me
  name: master-prd.aws.rolwynquadras.me
spec:
  image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220912
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - utility-us-east-1a

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prd.aws.rolwynquadras.me
  name: nodes
spec:
  image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220912
  machineType: t2.small
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - utility-us-east-1a

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prd.aws.rolwynquadras.me
  name: bastions
spec:
  associatePublicIp: true
  image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220912
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-east-1a